name: mon_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_config: ^2.0.2
  flutter_contacts: ^1.1.7+1
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  hexcolor: ^3.0.1
  permission_handler: ^11.3.1
  rename_app: ^1.3.2
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
